name: Generate Markdown Table of Contents

on:
  push:
    branches:
      - "*"

jobs:
  generate_toc:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Table of Contents
        uses: actions/markdown-toc@v1
        with:
          markdown_files: "docs/**/*.md"

          